### ISSUE TITLE
Simple match queries with (possibly?) incorrect syntax send back misleading results

### ISSUE THREAD

**Issue by isobelhooper** [graknlabs/grakn-python#22] opened 2017-07-26 13:54 UTC
I've been testing out the Grakn Python driver, and when I do a match query that has a variable name in it, I get results using that variable name:

    >>> from grakn.client import Graph
    >>> g = Graph(uri='http://localhost:4567')
    >>> g.execute("match $x isa person;")
    [{'x': {'isa': 'person', 'id': '20496'}}, {'x': {'isa': 'person', 'id': '20704'}}, {'x': {'isa': 'person', 'id': '28736'}}, {'x': {'isa': 'person', 'id': '32792'}}]
    >>> g.execute("match $x has identifier 'Bob' isa person;")
    [{'x': {'isa': 'person', 'id': '20496'}}]

However, if I miss out the variable name, I don't get any syntax errors, but I also get a list of empty dictionaries, one for each of the matching graph entities.

    >>> g.execute("match isa person;")
    [{}, {}, {}, {}]
    >>> g.execute("match has identifier 'Bob' isa person;")
    [{}]

Running either of these queries in the web shell gives me "No results were found for your query".

Should this be incorrect syntax, and if not, what should the actual behaviour of these queries be? The Python driver and the web shell give inconsistent results at the moment.

**Comment by aelred** [comment] 2017-08-02 13:33
Thanks for reporting this issue!

This is currently valid syntax so the empty results are expected. I had a go with the web shell, where I got the same results as Python.

In the graph view I get the same as you: "No results were found for your query". I'm not totally sure what should happen in this case. On the one hand, there _are_ technically results, just empty ones. On the other, there's nothing to display in the graph view, since the results do not contain any concepts.

**Comment by mikonapoli** [comment] 2017-12-08 13:01
@aelred is this still an issue?

**Comment by aelred** [comment] 2017-12-13 12:24
@mikonapoli the remaning issue was the "No results were found for your query" on the dashboard for queries such as `match isa person;`. I just tried it on `stable` and the issue is still there. So I'll log a bug for that and we can close this.

**Closed by aelred** 2017-12-13 12:24 UTC
